spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  data:
    redis:
      host: localhost
      port: 6379
