 spring:
   datasource:
      url: jdbc:mysql://localhost:3306/stock?useSSL=false&serverTimezone=Asia/Seoul
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root

    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
   data:
     redis:
       host: localhost
       port: 6379
